<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CadangandanPotensiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        
        $data = [
            // [
            //     'cadpot_id' => 1,
            //     'opco_id'=> 1, 
            //     'Jarak' => 3.2,
            //     'latitude' => -6.88402,
            //     'longitude' => 111.9278,
            //     'NO_ID' => 456000, // Assuming this should be an integer
            //     'Komoditi' => "Cad Batugamping",
            //     'Lokasi_IUP' => "IUP Temandang",
            //     'Tipe_SD_Cadangan' => "Cadangan Terbukti",
            //     'SD_Cadangan_ton' => 180290209,
            //     'Catatan' => "Luas 752,8 Hektar. Produksi 16,236,480 ton/tahun.",
            //     'Status_Penyelidikan' => "Operasi Produksi",
            //     'Acuan' => "RKAB Tahun 2022, PT Semen Indonesia (Persero) Tbk Kuari Batugamping Temandang",
            //     'Kabupaten' => "Tuban",
            //     'Kecamatan' => "Merakurak, Kerek",
            //     'Luas_ha' => 752.8,
            //     'Masa_Berlaku_IUP' => Carbon::create(2029, 5, 14),
            //     'Masa_Berlaku_PPKH' => Carbon::create(2029, 5, 14),
            // ],
            // [
            //     'cadpot_id' => 2,
            //     'opco_id'=> 1, 
            //     'Jarak' => 11.6,
            //     'latitude' => -6.892200,
            //     'longitude' => 111.954580,
            //     'NO_ID' => 456100, // Assuming this should be an integer
            //     'Komoditi' => "Cad Batugamping",
            //     'Lokasi_IUP' => "IUP Tuwiri",
            //     'Tipe_SD_Cadangan' => "Cadangan Terbukti",
            //     'SD_Cadangan_ton' => 160602000,
            //     'Catatan' => "CaO 46% - 54%, MgO < 2%, Luas 458,9 Hektar.",
            //     'Status_Penyelidikan' => "Operasi Produksi",
            //     'Acuan' => "RKAB Tahun 2022, PT Semen Indonesia (Persero) Tbk Kuari Batugamping Tuwiri",
            //     'Kabupaten' => "Tuban",
            //     'Kecamatan' => "Merakurak, Kerek",
            //     'Luas_ha' => 458.9,
            //     'Masa_Berlaku_IUP' => Carbon::create(2032, 3, 27),
            //     'Masa_Berlaku_PPKH' => Carbon::create(2032, 3, 27),
            // ],
            // [
            //     'cadpot_id' => 3,
            //     'opco_id'=> 1, 
            //     'Jarak' => 2.8,
            //     'latitude' => -6.850910,
            //     'longitude' => 111.936740,
            //     'NO_ID' => 456200, // Assuming this should be an integer
            //     'Komoditi' => "Cad Lempung",
            //     'Lokasi_IUP' => "IUP Tlogowaru",
            //     'Tipe_SD_Cadangan' => "Cadangan Terbukti",
            //     'SD_Cadangan_ton' => 4982366,
            //     'Catatan' => "Al2O3 6%-17%, Luas 120,04 Hektar, Rencana Produksi 1,217,736 ton/tahun.",
            //     'Status_Penyelidikan' => "Operasi Produksi",
            //     'Acuan' => "RKAB Tahun 2022, PT Semen Indonesia (Persero) Tbk Kuari Clay Tlogowaru",
            //     'Kabupaten' => "Tuban",
            //     'Kecamatan' => "Merakurak, Kerek",
            //     'Luas_ha' => 120.04,
            //     'Masa_Berlaku_IUP' => Carbon::create(2033, 8, 6),
            //     'Masa_Berlaku_PPKH' => null,
            // ],
            // [
            //     'cadpot_id' => 4,
            //     'opco_id'=> 1, 
            //     'Jarak' => 10.4,
            //     'latitude' => -6.83144,
            //     'longitude' => 111.90826,
            //     'NO_ID' => null,
            //     'Komoditi' => "Cad Lempung",
            //     'Lokasi_IUP' => "IUP Mliwang",
            //     'Tipe_SD_Cadangan' => "Cadangan Terbukti",
            //     'SD_Cadangan_ton' => 1789302,
            //     'Catatan' => null,
            //     'Status_Penyelidikan' => null,
            //     'Acuan' => null,
            //     'Kabupaten' => "Tuban",
            //     'Kecamatan' => "Kerek",
            //     'Luas_ha' => 201.6,
            //     'Masa_Berlaku_IUP' => Carbon::create(2022, 12, 31),
            //     'Masa_Berlaku_PPKH' => null,
            // ],
            // [
            //     'cadpot_id' => 5,
            //     'opco_id'=> 1, 
            //     'Jarak' => 6.6,
            //     'latitude' => -6.83671,
            //     'longitude' => 111.89629,
            //     'NO_ID' => null,
            //     'Komoditi' => "Cad Lempung",
            //     'Lokasi_IUP' => "IUP Tobo",
            //     'Tipe_SD_Cadangan' => "Cadangan Terbukti",
            //     'SD_Cadangan_ton' => 748651,
            //     'Catatan' => null,
            //     'Status_Penyelidikan' => null,
            //     'Acuan' => null,
            //     'Kabupaten' => "Tuban",
            //     'Kecamatan' => "Merakurak",
            //     'Luas_ha' => 5,
            //     'Masa_Berlaku_IUP' => Carbon::create(2024, 11, 15),
            //     'Masa_Berlaku_PPKH' => null,
            // ],
            // [
            //     'cadpot_id' => 6,
            //     'opco_id'=> 1, 
            //     'Jarak' => 5.7,
            //     'latitude' => -6.82047,
            //     'longitude' => 111.91368,
            //     'NO_ID' => null,
            //     'Komoditi' => "Cad Lempung",
            //     'Lokasi_IUP' => "IUP Karangasem",
            //     'Tipe_SD_Cadangan' => "Cadangan Terbukti",
            //     'SD_Cadangan_ton' => 2893654,
            //     'Catatan' => null,
            //     'Status_Penyelidikan' => null,
            //     'Acuan' => null,
            //     'Kabupaten' => "Tuban",
            //     'Kecamatan' => "Jenu",
            //     'Luas_ha' => 35.75,
            //     'Masa_Berlaku_IUP' => Carbon::create(2024, 11, 15),
            //     'Masa_Berlaku_PPKH' => null,
            // ],
            // [
            //     'cadpot_id' => 7,
            //     'opco_id'=> 1, 
            //     'Jarak' => 8.7,
            //     'latitude' => -6.89834,
            //     'longitude' => 111.92986,
            //     'NO_ID' => 252700, // Assuming this should be an integer
            //     'Komoditi' => "Pot Batugamping",
            //     'Lokasi_IUP' => "Merakurak",
            //     'Tipe_SD_Cadangan' => "SD Tertunjuk",
            //     'SD_Cadangan_ton' => 89642000,
            //     'Catatan' => "CaO rata-rata : 51,54%",
            //     'Status_Penyelidikan' => "Eksplorasi Rinci",
            //     'Acuan' => "652/Ga/88",
            //     'Kabupaten' => "Tuban",
            //     'Kecamatan' => "Kerek",
            //     'Luas_ha' => null,
            //     'Masa_Berlaku_IUP' => null,
            //     'Masa_Berlaku_PPKH' => null,
            // ],
            // [
            //     'cadpot_id' => 8,
            //     'opco_id'=> 1, 
            //     'Jarak' => 9.3,
            //     'latitude' => -6.90992,
            //     'longitude' => 111.87768,
            //     'NO_ID' => 252600, // Fixed to numeric value
            //     'Komoditi' => "Pot Batugamping",
            //     'Lokasi_IUP' => "Kerek",
            //     'Tipe_SD_Cadangan' => "SD Tertunjuk",
            //     'SD_Cadangan_ton' => 535773000,
            //     'Catatan' => "Baik",
            //     'Status_Penyelidikan' => "Eksplorasi Rinci",
            //     'Acuan' => "Neraca",
            //     'Kabupaten' => "Tuban",
            //     'Kecamatan' => "Kerek",
            //     'Luas_ha' => null,
            //     'Masa_Berlaku_IUP' => null,
            //     'Masa_Berlaku_PPKH' => null,
            // ],
            // [
            //     'cadpot_id' => 9,
            //     'opco_id'=> 1, 
            //     'Jarak' => 11.1,
            //     'latitude' => -6.89220,
            //     'longitude' => 111.96557,
            //     'NO_ID' => 362400, // Fixed to numeric value
            //     'Komoditi' => "Pot Batugamping",
            //     'Lokasi_IUP' => "Tiwiri Kulon",
            //     'Tipe_SD_Cadangan' => "Cadangan Terkira",
            //     'SD_Cadangan_ton' => 912576,
            //     'Catatan' => "IUP Aktif",
            //     'Status_Penyelidikan' => "Operasi Produksi",
            //     'Acuan' => "Sdr, Khusni Mubaroch, RKAB 2017",
            //     'Kabupaten' => "Tuban",
            //     'Kecamatan' => "Merakurak",
            //     'Luas_ha' => null,
            //     'Masa_Berlaku_IUP' => null,
            //     'Masa_Berlaku_PPKH' => null,
            // ],
            // [
            //     'cadpot_id' => 10,
            //     'opco_id'=> 1, 
            //     'Jarak' => 14,
            //     'latitude' => -6.90243,
            //     'longitude' => 112.01226,
            //     'NO_ID' => 252900, // Fixed to numeric value
            //     'Komoditi' => "Pot Batugamping",
            //     'Lokasi_IUP' => "Sugiharjo",
            //     'Tipe_SD_Cadangan' => "SD Terukur",
            //     'SD_Cadangan_ton' => 300000000,
            //     'Catatan' => "Komposisi kimia : CaO= 4,48 - 55,3%",
            //     'Status_Penyelidikan' => "Studi Kelayakan",
            //     'Acuan' => "Neraca",
            //     'Kabupaten' => "Tuban",
            //     'Kecamatan' => "Tuban",
            //     'Luas_ha' => null,
            //     'Masa_Berlaku_IUP' => null,
            //     'Masa_Berlaku_PPKH' => null,
            // ],
            // [
            //     'cadpot_id' => 11,
            //     'opco_id'=> 1, 
            //     'Jarak' => 32.8,
            //     'latitude' => -6.93651,
            //     'longitude' => 112.15508,
            //     'NO_ID' => 419000, // Fixed to numeric value
            //     'Komoditi' => "Pot Batugamping",
            //     'Lokasi_IUP' => "Leranwetan",
            //     'Tipe_SD_Cadangan' => "Cadangan Terbukti",
            //     'SD_Cadangan_ton' =>  529673,
            //     'Catatan' => "IUP 2018, Luas 1,32 Ha",
            //     'Status_Penyelidikan' => "Operasi Produksi",
            //     'Acuan' => "RKAB 2021, a,n Yusuf Wibisoid",
            //     'Kabupaten' => "Tuban",
            //     'Kecamatan' => "Palang",
            //     'Luas_ha' => 1.32,
            //     'Masa_Berlaku_IUP' => null,
            //     'Masa_Berlaku_PPKH' => null,
            // ],
            // [
            //     'cadpot_id' => 12,
            //     'opco_id'=> 1, 
            //     'Jarak' => 34.1,
            //     'latitude' => -7.044870,
            //     'longitude' => 111.986170,
            //     'NO_ID' => 252800, // Fixed to numeric value
            //     'Komoditi' => "Pot Batugamping",
            //     'Lokasi_IUP' => "Rengel",
            //     'Tipe_SD_Cadangan' => "SD Terukur",
            //     'SD_Cadangan_ton' =>  300000000,
            //     'Catatan' => "Komposisi kimia : CaO= 55,7 - 55,9 %",
            //     'Status_Penyelidikan' => "Studi Kelayakan",
            //     'Acuan' => "Neraca",
            //     'Kabupaten' => "Tuban",
            //     'Kecamatan' => "Rengel",
            //     'Luas_ha' => null,
            //     'Masa_Berlaku_IUP' => null,
            //     'Masa_Berlaku_PPKH' => null,
            // ],
            // [
            //     'cadpot_id' => 13,
            //     'opco_id'=> 1, 
            //     'Jarak' => 50.0,
            //     'latitude' => -7.130730,
            //     'longitude' => 112.102210,
            //     'NO_ID' => 250800, // Fixed to numeric value
            //     'Komoditi' => "Pot Batugamping",
            //     'Lokasi_IUP' => "Baureno",
            //     'Tipe_SD_Cadangan' => "SD Hipotetik",
            //     'SD_Cadangan_ton' =>  20923000,
            //     'Catatan' => "Komposisi kimia : CaO= 55,49%",
            //     'Status_Penyelidikan' => "55,49%",
            //     'Acuan' => "Neraca",
            //     'Kabupaten' => "Bojonegoro",
            //     'Kecamatan' => "Baureno",
            //     'Luas_ha' => null,
            //     'Masa_Berlaku_IUP' => null,
            //     'Masa_Berlaku_PPKH' => null,
            // ],
            // [
            //     'cadpot_id' => 14,
            //     'opco_id'=> 1, 
            //     'Jarak' => 9.9,
            //     'latitude' => -6.856700,
            //     'longitude' => 111.861480,
            //     'NO_ID' => 262000, // Fixed to numeric value
            //     'Komoditi' => "Pot Lempung",
            //     'Lokasi_IUP' => "Kerek",
            //     'Tipe_SD_Cadangan' => "SD Tertunjuk",
            //     'SD_Cadangan_ton' =>  19005000,
            //     'Catatan' => "Cukup baik",
            //     'Status_Penyelidikan' => "Eksplorasi Rinci",
            //     'Acuan' => "Neraca",
            //     'Kabupaten' => "Tuban",
            //     'Kecamatan' => "Kerek",
            //     'Luas_ha' => null,
            //     'Masa_Berlaku_IUP' => null,
            //     'Masa_Berlaku_PPKH' => null,
            // ],
            // [
            //     'cadpot_id' => 15,
            //     'opco_id'=> 1, 
            //     'Jarak' => 33.5,
            //     'latitude' => -7.017770,
            //     'longitude' => 111.969290,
            //     'NO_ID' => 401600, // Fixed to numeric value
            //     'Komoditi' => "Pot Lempung",
            //     'Lokasi_IUP' => "Banyubang",
            //     'Tipe_SD_Cadangan' => "Cadangan Terbukti",
            //     'SD_Cadangan_ton' =>  71530,
            //     'Catatan' => "Luas 3,16 Ha, Asumsi Bj 2,5 ton/m3",
            //     'Status_Penyelidikan' => "2,5 ton/m3",
            //     'Acuan' => "Tabulasi Rekon Minerba Tahun 2020, Sdr Mukono",
            //     'Kabupaten' => "Tuban",
            //     'Kecamatan' => "Grabangan",
            //     'Luas_ha' => 3.16,
            //     'Masa_Berlaku_IUP' => null,
            //     'Masa_Berlaku_PPKH' => null,
            // ],
            // [
            //     'cadpot_id' => 16,
            //     'opco_id'=> 1, 
            //     'Jarak' => 17.4,
            //     'latitude' => -6.795490,
            //     'longitude' =>-6.795490,
            //     'NO_ID' => 263200, // Fixed to numeric value
            //     'Komoditi' => "Pot Pasirkuarsa",
            //     'Lokasi_IUP' => "Tasikharjo",
            //     'Tipe_SD_Cadangan' => "SD Hipotetik",
            //     'SD_Cadangan_ton' =>  2000000,
            //     'Catatan' => "Sudah dianalisis",
            //     'Status_Penyelidikan' => "Survei Tinjau",
            //     'Acuan' => "Neraca",
            //     'Kabupaten' => "Tuban",
            //     'Kecamatan' => "Jenu",
            //     'Luas_ha' => null,
            //     'Masa_Berlaku_IUP' => null,
            //     'Masa_Berlaku_PPKH' => null,
            // ],
            // [
            //     'cadpot_id' => 17,
            //     'opco_id'=> 2, 
            //     'Jarak' => 9.8,
            //     'latitude' => -6.86877,
            //     'longitude' => 111.51146,
            //     'No_ID' => 360900,
            //     'Komoditi' => "Cad Batugamping",
            //     'Lokasi_IUP' => "IUP Tegaldowo",
            //     'Tipe_SD_Cadangan' => "Cadangan Terbukti",
            //     'SD_Cadangan_ton' => 255331678,
            //     'Catatan' => "Luas sebaran 293,10 ha, kandungan rata-rata CaO 34,53%-55,85%, MgO 0,02%-24,99%, SiO2 0,01%-33,47%, Al2O3 0,01%-4,64%, dan Fe2O3 0.00%-4.88%", // Kutip seluruh catatan
            //     'Status_Penyelidikan' => "Operasi Produksi",
            //     'Acuan' => "PT Semen Indonesia, Lapoan Eksplorasi, 2016", // Hapus tanda koma di awal
            //     'Kabupaten' => "Rembang",
            //     'Kecamatan' => "Gunem",
            //     'Luas_ha' => 293.1, // Hapus tanda kutip dan koma
            //     'masa_berlaku_iup' => Carbon::create(2037, 3, 2),
            //     'masa_berlaku_ppkh' => null,
            // ],
            // [
            //     'cadpot_id' => 18,
            //     'opco_id'=> 2, 
            //     'Jarak' =>  5.1 , 
            //     'latitude' => -6.86935,  // Latitude
            //     'longitude' => 111.46668, // Longitude
            //     'No_ID' => null, 
            //     'Komoditi' => "Cad Lempung",
            //     'Lokasi_IUP' => "IUP Kajar",
            //     'Tipe_SD_Cadangan' => " Cadangan Terbukti",
            //     'SD_Cadangan_ton' => 14983796, 
            //     'Catatan' => null,
            //     'Status_Penyelidikan' => null,
            //     'Acuan' => null,
            //     'Kabupaten' => "Rembang",
            //     'Kecamatan' => "Gunem",
            //     'Luas_ha' => 98.9,  
            //     'masa_berlaku_iup' =>Carbon::create(2037, 3, 8),
            //     'masa_berlaku_ppkh' =>Carbon::create(2037, 3, 8),
            // ],
            // [
            //     'cadpot_id' => 19,
            //     'opco_id'=> 2, 
            //     'Jarak' =>   1.6, 
            //     'latitude' => -6.86809,  // Latitude
            //     'longitude' => 111.44211, // Longitude
            //     'No_ID' => 237900, 
            //     'Komoditi' => "Pot Batugamping",
            //     'Lokasi_IUP' => "Kadiwono",
            //     'Tipe_SD_Cadangan' => "SD HIpotetik",
            //     'SD_Cadangan_ton' => 250000000, 
            //     'Catatan' => " CaO = 43,38%; MgO = 0,25% ",
            //     'Status_Penyelidikan' => "Survei Tinjau",
            //     'Acuan' => "Neraca",
            //     'Kabupaten' => "Rembang",
            //     'Kecamatan' => "Bulu",
            //     'Luas_ha' =>null,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            // [
            //     'cadpot_id' => 20,
            //     'opco_id'=> 2, 
            //     'Jarak' => 9.8, 
            //     'latitude' => -6.86264,  // Latitude
            //     'longitude' => 111.51009, // Longitude
            //     'No_ID' => 238200, 
            //     'Komoditi' => "Pot Batugamping",
            //     'Lokasi_IUP' => "Tegaldowo",
            //     'Tipe_SD_Cadangan' => "SD Tertunjuk",
            //     'SD_Cadangan_ton' => 525658000, 
            //     'Catatan' => "Luas sebaran = 400 Ha, medan sulit",
            //     'Status_Penyelidikan' => "Eksplorasi Rinci",
            //     'Acuan' => "Neraca",
            //     'Kabupaten' => "Rembang",
            //     'Kecamatan' => "Gunem",
            //     'Luas_ha' => 400,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            // [
            //     'cadpot_id' => 21,
            //     'opco_id'=> 2, 
            //     'Jarak' => 9.8, 
            //     'latitude' => -6.87354,  // Latitude
            //     'longitude' => 111.52108, // Longitude
            //     'No_ID' => 238100, 
            //     'Komoditi' => "Pot Batugamping",
            //     'Lokasi_IUP' => "Tegaldowo",
            //     'Tipe_SD_Cadangan' => " SD Hipotetik",
            //     'SD_Cadangan_ton' =>250000000, 
            //     'Catatan' => "CaO = 52,76%; MgO = 2,27%",
            //     'Status_Penyelidikan' => "Survei Tinjau",
            //     'Acuan' => "Neraca",
            //     'Kabupaten' => "Rembang",
            //     'Kecamatan' => "Gunem",
            //     'Luas_ha' => null,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            // [
            //     'cadpot_id' => 22,
            //     'opco_id'=> 2, 
            //     'Jarak' => 9.8, 
            //     'latitude' => -6.87423,  // Latitude
            //     'longitude' => 111.53069, // Longitude
            //     'No_ID' => 360500, 
            //     'Komoditi' => "Pot Batugamping",
            //     'Lokasi_IUP' => "Tegaldowo",
            //     'Tipe_SD_Cadangan' => "SD Terukur",
            //     'SD_Cadangan_ton' => 122582795, 
            //     'Catatan' => "Luas IUP 482 Ha",
            //     'Status_Penyelidikan' => "Operasi Produksi",
            //     'Acuan' => "PT Sinar Asia Fortuna , Lapoan Eksplorasi, 2003",
            //     'Kabupaten' => "Rembang",
            //     'Kecamatan' => "Gunem, Sale",
            //     'Luas_ha' => 482,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            // [
            //     'cadpot_id' => 23,
            //     'opco_id'=> 2, 
            //     'Jarak' => 13.6, 
            //     'latitude' => -6.78392,  // Latitude
            //     'longitude' => 111.47782, // Longitude
            //     'No_ID' => 238300, 
            //     'Komoditi' => "Pot Batugamping",
            //     'Lokasi_IUP' => "Gambiran, Pamotan",
            //     'Tipe_SD_Cadangan' => "SD Tertunjuk",
            //     'SD_Cadangan_ton' => 364975000, 
            //     'Catatan' => "Luas sebaran = 675 Ha, medan mudah",
            //     'Status_Penyelidikan' => "Eksplorasi Rinci",
            //     'Acuan' => "Neraca",
            //     'Kabupaten' => "Rembang",
            //     'Kecamatan' => "Pamotan",
            //     'Luas_ha' => 675,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            // [
            //     'cadpot_id' => 24,
            //     'opco_id'=> 2, 
            //     'Jarak' => 14, 
            //     'latitude' => -6.88264,  // Latitude
            //     'longitude' => 111.52616, // Longitude
            //     'No_ID' => 439200, 
            //     'Komoditi' => "Pot Batugamping",
            //     'Lokasi_IUP' => "Tahunan",
            //     'Tipe_SD_Cadangan' => "Cadangan Terbukti",
            //     'SD_Cadangan_ton' => 477597, 
            //     'Catatan' => "Luas 3,20 Hektar",
            //     'Status_Penyelidikan' => null,
            //     'Acuan' => "CV Alam Terang Perkasa, RKAB 2022",
            //     'Kabupaten' => "Rembang",
            //     'Kecamatan' => "Sale",
            //     'Luas_ha' => 3.2,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            // [
            //     'cadpot_id' => 25,
            //     'opco_id'=> 2, 
            //     'Jarak' => 14.4, 
            //     'latitude' => -6.87992,  // Latitude
            //     'longitude' => 111.5344, // Longitude
            //     'No_ID' => 439100, 
            //     'Komoditi' => "Pot Batugamping",
            //     'Lokasi_IUP' => "Tahunan",
            //     'Tipe_SD_Cadangan' => "Cadangan Terbukti",
            //     'SD_Cadangan_ton' =>  309459, 
            //     'Catatan' => "Luas 1,36 Hektar",
            //     'Status_Penyelidikan' => null,
            //     'Acuan' => "CV Alam Mulyo Putra, RKAB 2022",
            //     'Kabupaten' => "Rembang",
            //     'Kecamatan' => "Sale",
            //     'Luas_ha' => 1.36,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            // [
            //     'cadpot_id' => 26,
            //     'opco_id'=> 2, 
            //     'Jarak' => 14.4, 
            //     'latitude' => -6.88281,  // Latitude
            //     'longitude' =>  111.53491, // Longitude
            //     'No_ID' => 440400, 
            //     'Komoditi' => "Pot Batugamping",
            //     'Lokasi_IUP' => "Tahunan",
            //     'Tipe_SD_Cadangan' => "Cadangan Terbukti",
            //     'SD_Cadangan_ton' => 2444955, 
            //     'Catatan' => "Luas 7,12 Hektar",
            //     'Status_Penyelidikan' => null,
            //     'Acuan' => "CV Bio Alam Indo, RKAB 2022",
            //     'Kabupaten' => "Rembang",
            //     'Kecamatan' => "Sale",
            //     'Luas_ha' => 7.12,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            // [
            //     'cadpot_id' => 27,
            //     'opco_id'=> 2, 
            //     'Jarak' => 14, 
            //     'latitude' => -6.88605,  // Latitude
            //     'longitude' => 111.53079, // Longitude
            //     'No_ID' => 440300, 
            //     'Komoditi' => "Pot Batugamping",
            //     'Lokasi_IUP' => "Tahunan",
            //     'Tipe_SD_Cadangan' => "Cadangan Terbukti",
            //     'SD_Cadangan_ton' =>  262213, 
            //     'Catatan' => "Luas 1,16 Hektar",
            //     'Status_Penyelidikan' => null,
            //     'Acuan' => "CV Bio Alam Indo, RKAB 2022",
            //     'Kabupaten' => "Rembang",
            //     'Kecamatan' => "Sale",
            //     'Luas_ha' => 1.16,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            // [
            //     'cadpot_id' => 28,
            //     'opco_id'=> 2, 
            //     'Jarak' => 14.4, 
            //     'latitude' => -6.88384,  // Latitude
            //     'longitude' => 111.53697, // Longitude
            //     'No_ID' => 439500, 
            //     'Komoditi' => "Pot Batugamping",
            //     'Lokasi_IUP' => "Tahunan",
            //     'Tipe_SD_Cadangan' => "Cadangan Terbukti",
            //     'SD_Cadangan_ton' =>   826200, 
            //     'Catatan' => "Luas 7,30 Hektar",
            //     'Status_Penyelidikan' => null,
            //     'Acuan' => "CV Aveido, RKAB 2022",
            //     'Kabupaten' => "Rembang",
            //     'Kecamatan' => "Sale",
            //     'Luas_ha' => 7.3,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            // [
            //     'cadpot_id' => 29,
            //     'opco_id'=> 2, 
            //     'Jarak' =>  24.9, 
            //     'latitude' => -6.85633,  // Latitude
            //     'longitude' => 111.31017, // Longitude
            //     'No_ID' => 238000, 
            //     'Komoditi' => "Pot Batugamping",
            //     'Lokasi_IUP' => "Mlatirejo",
            //     'Tipe_SD_Cadangan' => " SD Tertunjuk",
            //     'SD_Cadangan_ton' => 364975000, 
            //     'Catatan' => "Luas sebaran = 3025 Ha, medan sulit",
            //     'Status_Penyelidikan' => "Eksplorasi Rinci",
            //     'Acuan' => "Neraca",
            //     'Kabupaten' => "Rembang",
            //     'Kecamatan' => "Bulu",
            //     'Luas_ha' => 3025,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            // [
            //     'cadpot_id' => 30,
            //     'opco_id'=> 2, 
            //     'Jarak' => 15.4, 
            //     'latitude' => -6.95102,  // Latitude
            //     'longitude' => 111.41246, // Longitude
            //     'No_ID' => 241800, 
            //     'Komoditi' => "Pot Lempung",
            //     'Lokasi_IUP' => "Temurejo",
            //     'Tipe_SD_Cadangan' => " SD Tertunjuk ",
            //     'SD_Cadangan_ton' => 12760000, 
            //     'Catatan' => "Luas sebaran = 492 Ha, 3 km dari kota kecamatan",
            //     'Status_Penyelidikan' => "Eksplorasi Rinci",
            //     'Acuan' => "Neraca",
            //     'Kabupaten' => "Blora",
            //     'Kecamatan' => "Tunjungan",
            //     'Luas_ha' => 492,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            // [
            //     'cadpot_id' => 31,
            //     'opco_id'=> 2, 
            //     'Jarak' =>  19.8, 
            //     'latitude' => -6.75482,  // Latitude
            //     'longitude' =>  111.4711, // Longitude
            //     'No_ID' => 242800, 
            //     'Komoditi' => "Pot Lempung",
            //     'Lokasi_IUP' => "Sumberejo",
            //     'Tipe_SD_Cadangan' => "SD Tereka",
            //     'SD_Cadangan_ton' => 29230000, 
            //     'Catatan' => "Mutu belum diketahui",
            //     'Status_Penyelidikan' => "Prospeksi",
            //     'Acuan' => "Neraca",
            //     'Kabupaten' => "Rembang",
            //     'Kecamatan' => "Pamotan",
            //     'Luas_ha' => null,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            // [
            //     'cadpot_id' => 32,
            //     'opco_id'=> 2, 
            //     'Jarak' => 23.0, 
            //     'latitude' => -6.78755,  // Latitude
            //     'longitude' => 111.56887, // Longitude
            //     'No_ID' => 242900, 
            //     'Komoditi' => "Pot Lempung",
            //     'Lokasi_IUP' => "Sambiroto",
            //     'Tipe_SD_Cadangan' => "SD Hipotetik",
            //     'SD_Cadangan_ton' => 10500000, 
            //     'Catatan' => null,
            //     'Status_Penyelidikan' => "Survey Tinjau",
            //     'Acuan' => "Neraca",
            //     'Kabupaten' => "Rembang",
            //     'Kecamatan' => "Sedan",
            //     'Luas_ha' => null,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            // [
            //     'cadpot_id' => 33,
            //     'opco_id'=> 2,
            //     'Jarak' => 28.9, 
            //     'latitude' =>-6.73900,  // Latitude
            //     'longitude' => 111.43539, // Longitude
            //     'No_ID' => 242700, 
            //     'Komoditi' => "Pot Lempung",
            //     'Lokasi_IUP' => "Jeruk",
            //     'Tipe_SD_Cadangan' => "SD Hipotetik",
            //     'SD_Cadangan_ton' => 7500000, 
            //     'Catatan' => null,
            //     'Status_Penyelidikan' => "Survey Tinjau",
            //     'Acuan' => "Neraca",
            //     'Kabupaten' => "Rembang",
            //     'Kecamatan' => "Pancur",
            //     'Luas_ha' => 492,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            // [
            //     'cadpot_id' => 34,
            //     'opco_id'=> 2,
            //     'Jarak' => 29.3, 
            //     'latitude' =>-6.984010,  // Latitude
            //     'longitude' => 111.535920, // Longitude
            //     'No_ID' => 242000, 
            //     'Komoditi' => "Pot Lempung",
            //     'Lokasi_IUP' => "Singonegoro",
            //     'Tipe_SD_Cadangan' => "SD Tertunjuk",
            //     'SD_Cadangan_ton' => 4200000, 
            //     'Catatan' => "Luas sebaran = 140 Ha",
            //     'Status_Penyelidikan' => "Eksplorasi Rinci",
            //     'Acuan' => "Neraca",
            //     'Kabupaten' => "Blora",
            //     'Kecamatan' => "Jiken",
            //     'Luas_ha' => 140,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            // [
            //     'cadpot_id' => 35,
            //     'opco_id'=> 2,
            //     'Jarak' => 29.3, 
            //     'latitude' =>-6.984010,  // Latitude
            //     'longitude' => 111.535920, // Longitude
            //     'No_ID' => 242000, 
            //     'Komoditi' => "Pot Lempung",
            //     'Lokasi_IUP' => "Singonegoro",
            //     'Tipe_SD_Cadangan' => "SD Tertunjuk",
            //     'SD_Cadangan_ton' => 4200000, 
            //     'Catatan' => "Luas sebaran = 140 Ha",
            //     'Status_Penyelidikan' => "Eksplorasi Rinci",
            //     'Acuan' => "Neraca",
            //     'Kabupaten' => "Blora",
            //     'Kecamatan' => "Jiken",
            //     'Luas_ha' => 140,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            
            // [
            //     'cadpot_id' => 36,
            //     'opco_id'=> 2,
            //     'Jarak' => 32.6, 
            //     'latitude' =>-6.991510,  // Latitude
            //     'longitude' => 111.299020, // Longitude
            //     'No_ID' => 241900, 
            //     'Komoditi' => "Pot Lempung",
            //     'Lokasi_IUP' => "Harjowinangun",
            //     'Tipe_SD_Cadangan' => "SD Tertunjuk",
            //     'SD_Cadangan_ton' => 9000000, 
            //     'Catatan' => "Luas sebaran = 300 Ha, 5 km dari kota kecamatan",
            //     'Status_Penyelidikan' => "Eksplorasi Rinci",
            //     'Acuan' => "Neraca",
            //     'Kabupaten' => "Blora",
            //     'Kecamatan' => "Ngawen",
            //     'Luas_ha' => 300,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            
            // [
            //     'cadpot_id' => 37,
            //     'opco_id'=> 2,
            //     'Jarak' => 33.9, 
            //     'latitude' =>-6.724410,  // Latitude
            //     'longitude' => 111.272240, // Longitude
            //     'No_ID' => 242600, 
            //     'Komoditi' => "Pot Lempung",
            //     'Lokasi_IUP' => "Sambiyan",
            //     'Tipe_SD_Cadangan' => "SD Hipotetik",
            //     'SD_Cadangan_ton' => 105000000, 
            //     'Catatan' => "SiO2 : 85,88 %; Al2O3 : 4,49 %; Fe2O3 : 4,39 %",
            //     'Status_Penyelidikan' => "Survey Tinjau",
            //     'Acuan' => "Neraca",
            //     'Kabupaten' => "Rembang",
            //     'Kecamatan' => "Kaliori",
            //     'Luas_ha' => null,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            
            // [
            //     'cadpot_id' => 38,
            //     'opco_id'=> 2,
            //     'Jarak' => 40.1, 
            //     'latitude' =>-6.790550,  // Latitude
            //     'longitude' => 111.695220, // Longitude
            //     'No_ID' => 400400, 
            //     'Komoditi' => "Pot Lempung",
            //     'Lokasi_IUP' => "Lestari",
            //     'Tipe_SD_Cadangan' => "Cadangan Terbukti",
            //     'SD_Cadangan_ton' => 27080, 
            //     'Catatan' => "Luas 6,35 Ha, Asumsi Bj 2,5 ton/m3",
            //     'Status_Penyelidikan' => "Operasi Produksi",
            //     'Acuan' => "Tabulasi Rekon Minerba Tahun 2020, SDR SUGIHARNI",
            //     'Kabupaten' => "Tuban",
            //     'Kecamatan' => "Bancar",
            //     'Luas_ha' => 6.35,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            
            // [
            //     'cadpot_id' => 39,
            //     'opco_id'=> 2,
            //     'Jarak' => 45.8, 
            //     'latitude' =>-6.844410,  // Latitude
            //     'longitude' => 111.167870, // Longitude
            //     'No_ID' => 242500, 
            //     'Komoditi' => "Pot Lempung",
            //     'Lokasi_IUP' => "Pucakwangi",
            //     'Tipe_SD_Cadangan' => "SD Tertunjuk",
            //     'SD_Cadangan_ton' => 4420000, 
            //     'Catatan' => "Luas sebaran = 26 Ha",
            //     'Status_Penyelidikan' => "Eksplorasi Rinci",
            //     'Acuan' => "Neraca",
            //     'Kabupaten' => "Pati",
            //     'Kecamatan' => "Pucakwangi",
            //     'Luas_ha' => 26,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            
            // [
            //     'cadpot_id' => 40,
            //     'opco_id'=> 2,
            //     'Jarak' => 47.7, 
            //     'latitude' =>-6.629200,  // Latitude
            //     'longitude' => 111.491420, // Longitude
            //     'No_ID' => 243000, 
            //     'Komoditi' => "Pot Lempung",
            //     'Lokasi_IUP' => "Pangkalan",
            //     'Tipe_SD_Cadangan' => "SD Tertunjuk",
            //     'SD_Cadangan_ton' => 23450000, 
            //     'Catatan' => "Luas sebaran = 30 Ha, medan mudah",
            //     'Status_Penyelidikan' => "Eksplorasi Rinci",
            //     'Acuan' => "Neraca",
            //     'Kabupaten' => "Rembang",
            //     'Kecamatan' => "Sluke",
            //     'Luas_ha' => 30,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            
            // [
            //     'cadpot_id' => 41,
            //     'opco_id'=> 2,
            //     'Jarak' => 48.2, 
            //     'latitude' =>-6.632610,  // Latitude
            //     'longitude' => 111.498290, // Longitude
            //     'No_ID' => 243100, 
            //     'Komoditi' => "Pot Lempung",
            //     'Lokasi_IUP' => "Sluke",
            //     'Tipe_SD_Cadangan' => "SD Tertunjuk",
            //     'SD_Cadangan_ton' => 23450000, 
            //     'Catatan' => "Luas sebaran = 30 Ha, medan mudah",
            //     'Status_Penyelidikan' => "Eksplorasi Rinci",
            //     'Acuan' => "Neraca",
            //     'Kabupaten' => "Rembang",
            //     'Kecamatan' => "Sluke",
            //     'Luas_ha' => 30,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],          

            // [
            //     'cadpot_id' => 42,
            //     'opco_id'=> 2,
            //     'Jarak' => 21.7, 
            //     'latitude' =>-6.828580,  // Latitude
            //     'longitude' => 111.536290, // Longitude
            //     'No_ID' => 442600, 
            //     'Komoditi' => "Pot Pasirkuarsa",
            //     'Lokasi_IUP' => "Mojosari",
            //     'Tipe_SD_Cadangan' => "Cadangan Terbukti",
            //     'SD_Cadangan_ton' => 354738, 
            //     'Catatan' => "Luas 4,13 Hektar",
            //     'Status_Penyelidikan' => null,
            //     'Acuan' => "CV Pasir Mas, RKAB 2022",
            //     'Kabupaten' => "Rembang",
            //     'Kecamatan' => "Sedan",
            //     'Luas_ha' => 4.13,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            
            // [
            //     'cadpot_id' => 43,
            //     'opco_id'=> 2,
            //     'Jarak' => 25.5, 
            //     'latitude' =>-6.789380,  // Latitude
            //     'longitude' => 111.558380, // Longitude
            //     'No_ID' => 244300, 
            //     'Komoditi' => "Pot Pasirkuarsa",
            //     'Lokasi_IUP' => "Gesikan",
            //     'Tipe_SD_Cadangan' => "SD Tereka",
            //     'SD_Cadangan_ton' => 1000000, 
            //     'Catatan' => "Produksi",
            //     'Status_Penyelidikan' => "Prospeksi",
            //     'Acuan' => "Dinas Pertambangan Prop.Jawa Tengah th. Okt. 1997",
            //     'Kabupaten' => "Rembang",
            //     'Kecamatan' => "Sedan",
            //     'Luas_ha' => null,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            // [
            //     'cadpot_id' => 44,
            //     'opco_id'=> 2,
            //     'Jarak' => 24.2, 
            //     'latitude' =>-6.779840,  // Latitude
            //     'longitude' => 111.539840, // Longitude
            //     'No_ID' => 244400, 
            //     'Komoditi' => "Pot Pasirkuarsa",
            //     'Lokasi_IUP' => "Karas",
            //     'Tipe_SD_Cadangan' => "SD Hipotetik",
            //     'SD_Cadangan_ton' => 20000000, 
            //     'Catatan' => null,
            //     'Status_Penyelidikan' => "Neraca",
            //     'Acuan' => "Dinas Pertambangan Prop.Jawa Tengah th. Okt. 1997",
            //     'Kabupaten' => "Rembang",
            //     'Kecamatan' => "Sedan",
            //     'Luas_ha' => null,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            // [
            //     'cadpot_id' => 45,
            //     'opco_id'=> 2,
            //     'Jarak' => 26.4, 
            //     'latitude' =>-6.778470,  // Latitude
            //     'longitude' => 111.593400, // Longitude
            //     'No_ID' => 244200, 
            //     'Komoditi' => "Pot Pasirkuarsa",
            //     'Lokasi_IUP' => "Lodan Kulon",
            //     'Tipe_SD_Cadangan' => "SD Tertunjuk",
            //     'SD_Cadangan_ton' => 26500000, 
            //     'Catatan' => "Produksi, Luas sebaran 300 Ha, medan mudah",
            //     'Status_Penyelidikan' => "Eksplorasi Rinci",
            //     'Acuan' => "Dinas Pertambangan Prop.Jawa Tengah th. Okt. 1997",
            //     'Kabupaten' => "Rembang",
            //     'Kecamatan' => "Sarang",
            //     'Luas_ha' => 300,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            // [
            //     'cadpot_id' => 46,
            //     'opco_id'=> 2,
            //     'Jarak' => 37.4, 
            //     'latitude' =>-6.794430,  // Latitude
            //     'longitude' => 111.655480, // Longitude
            //     'No_ID' => 437600, 
            //     'Komoditi' => "Pot Pasirkuarsa",
            //     'Lokasi_IUP' => "Tawangrejo",
            //     'Tipe_SD_Cadangan' => "Cadangan Terbukti",
            //     'SD_Cadangan_ton' => 445725, 
            //     'Catatan' => "Luas 6,1 Hektar",
            //     'Status_Penyelidikan' => null,
            //     'Acuan' => "Agus Santosa, RKAB 2022",
            //     'Kabupaten' => "Rembang",
            //     'Kecamatan' => "Sarang",
            //     'Luas_ha' => 6.1,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            // [
            //     'cadpot_id' => 47,
            //     'opco_id'=> 2,
            //     'Jarak' => 35.6, 
            //     'latitude' =>-6.686010,  // Latitude
            //     'longitude' => 111.608780, // Longitude
            //     'No_ID' => 244100, 
            //     'Komoditi' => "Pot Pasirkuarsa",
            //     'Lokasi_IUP' => "Kragan",
            //     'Tipe_SD_Cadangan' => "SD Tertunjuk",
            //     'SD_Cadangan_ton' => 90000, 
            //     'Catatan' => "Luas sebaran = 87 Ha, medan mudah, SiO2=69,37-82,7...",
            //     'Status_Penyelidikan' => "Eksplorasi Rinci",
            //     'Acuan' => "Neraca",
            //     'Kabupaten' => "Rembang",
            //     'Kecamatan' => "Kragan",
            //     'Luas_ha' => 87,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            // [
            //     'cadpot_id' => 48,
            //     'opco_id'=> 2,
            //     'Jarak' => 38.2, 
            //     'latitude' =>-6.790300,  // Latitude
            //     'longitude' => 111.671170, // Longitude
            //     'No_ID' => 400600, 
            //     'Komoditi' => "Pot Pasirkuarsa",
            //     'Lokasi_IUP' => "Tlogoagung",
            //     'Tipe_SD_Cadangan' => "Cadangan Terbukti",
            //     'SD_Cadangan_ton' => 1104001, 
            //     'Catatan' => "Luas 4,75 Ha. Asumsi Bj 2,65 ton/m3",
            //     'Status_Penyelidikan' => "Eksplorasi",
            //     'Acuan' => "Tabulasi Rekon Minerba Tahun 2020, Sdr Agus santoso",
            //     'Kabupaten' => "Tuban",
            //     'Kecamatan' => "Bancar",
            //     'Luas_ha' => 4.75,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            // [
            //     'cadpot_id' => 49,
            //     'opco_id'=> 2,
            //     'Jarak' => 38.2, 
            //     'latitude' =>-6.787580,  // Latitude
            //     'longitude' => 111.671170, // Longitude
            //     'No_ID' => 401100, 
            //     'Komoditi' => "Pot Pasirkuarsa",
            //     'Lokasi_IUP' => "Tlogoagung",
            //     'Tipe_SD_Cadangan' => "Cadangan Terbukti",
            //     'SD_Cadangan_ton' => 454835, 
            //     'Catatan' => "Luas 1,87 Ha. Asumsi Bj 2,65 ton/m3",
            //     'Status_Penyelidikan' => "Operasi Produksi",
            //     'Acuan' => "Tabulasi Rekon Minerba Tahun 2020, Sdr Mahsum",
            //     'Kabupaten' => "Tuban",
            //     'Kecamatan' => "Bancar",
            //     'Luas_ha' => 1.87,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            // [
            //     'cadpot_id' => 50,
            //     'opco_id'=> 2,
            //     'Jarak' => 39.2, 
            //     'latitude' =>-6.834210,  // Latitude
            //     'longitude' =>111.677970, // Longitude
            //     'No_ID' => 401200, 
            //     'Komoditi' => "Pot Pasirkuarsa",
            //     'Lokasi_IUP' => "Ngepon",
            //     'Tipe_SD_Cadangan' => "Cadangan Terbukti",
            //     'SD_Cadangan_ton' => 1082774, 
            //     'Catatan' => "Luas 2,62 Hektar. Rencana Produksi tahun 2022, 124",
            //     'Status_Penyelidikan' => "Operasi Produksi",
            //     'Acuan' => "RKAB Tahun 2022, A.n. Agus Santoso",
            //     'Kabupaten' => "Tuban",
            //     'Kecamatan' => "Jatirogo",
            //     'Luas_ha' => 2.62,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            // [
            //     'cadpot_id' => 51,
            //     'opco_id'=> 2,
            //     'Jarak' => 45.8, 
            //     'latitude' =>-6.641990,  // Latitude
            //     'longitude' => 111.512670, // Longitude
            //     'No_ID' => 442500, 
            //     'Komoditi' => "Pot Tras",
            //     'Lokasi_IUP' => "Jatisari dan Sluke",
            //     'Tipe_SD_Cadangan' => "Cadangan Terbukti",
            //     'SD_Cadangan_ton' => 1262587, 
            //     'Catatan' => "Luas 12,93 Hektar",
            //     'Status_Penyelidikan' => null,
            //     'Acuan' => "CV Pasir Mas, RKAB 2022",
            //     'Kabupaten' => "Rembang",
            //     'Kecamatan' => "Sluke",
            //     'Luas_ha' => 12.93,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            // [
            //     'cadpot_id' => 52,
            //     'opco_id'=> 2,
            //     'Jarak' => 45.0, 
            //     'latitude' =>-6.636540,  // Latitude
            //     'longitude' => 111.517480, // Longitude
            //     'No_ID' => 440200, 
            //     'Komoditi' => "Pot Tras",
            //     'Lokasi_IUP' => "Sluke",
            //     'Tipe_SD_Cadangan' => "Cadangan Terbukti",
            //     'SD_Cadangan_ton' => 107250, 
            //     'Catatan' => "Luas 9,92 Hektar",
            //     'Status_Penyelidikan' => null,
            //     'Acuan' => "CV Robyong Mulyo Abadi, RKAB 2022",
            //     'Kabupaten' => "Rembang",
            //     'Kecamatan' => "Sluke",
            //     'Luas_ha' => 9.92,  
            //     'masa_berlaku_iup' =>null,
            //     'masa_berlaku_ppkh' =>null,
            // ],
            // [
            //     'cadpot_id' => 53,
            //     'opco_id'=> 3,
            //     'Jarak' =>  11.3, 
            //     'latitude' =>-6.84107,  // Latitude
            //     'longitude' => 111.86257, // Longitude
            //     'No_ID' => 418200, 
            //     'Komoditi' => "Cad Batugamping",
            //     'Lokasi_IUP' => "IUP Sawir",
            //     'Tipe_SD_Cadangan' => "Cadangan Terbukti",
            //     'SD_Cadangan_ton' =>548047984, 
            //     'Catatan' => "IUP 2020. Luas 573,83 Ha",
            //     'Status_Penyelidikan' => "Operasi Produksi",
            //     'Acuan' => "Persetujuan RKAB 2021. PT Solusi Bangun Indonesia Tbk",
            //     'Kabupaten' => "Tuban",
            //     'Kecamatan' => "Tambakboyo, Kerek",
            //     'Luas_ha' => 573.83,  
            //     'masa_berlaku_iup' => Carbon::create(2034, 12, 12),
            //     'masa_berlaku_ppkh' =>Carbon::create(2034, 12, 12),
            // ],
            [
                'cadpot_id' => 54,
                'opco_id'=> 3,
                'Jarak' =>10.4, 
                'latitude' =>-6.82541,  // Latitude
                'longitude' => 111.8965, // Longitude
                'No_ID' => 418100, 
                'Komoditi' => "Cad Tanah Liat",
                'Lokasi_IUP' => "IUP Mliwang 1",
                'Tipe_SD_Cadangan' => "Cadangan Terbukti",
                'SD_Cadangan_ton' => 10000000, 
                'Catatan' => "IUP 2020, Luas 33 Ha",
                'Status_Penyelidikan' => "Operasi Produksi",
                'Acuan' => "Persetujuan RKAB 2021. PT Solusi Bangun Indonesia Tbk",
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Kerek",
                'Luas_ha' => 33,  
                'masa_berlaku_iup' => Carbon::create(2024, 12, 12),
                'masa_berlaku_ppkh' =>Carbon::create(2024, 12, 12),
            ],
            [
                'cadpot_id' => 55,
                'opco_id'=> 3,
                'Jarak' =>10.4, 
                'latitude' =>-6.83099,  // Latitude
                'longitude' => 111.87674, // Longitude
                'No_ID' => null, 
                'Komoditi' => "Cad Tanah Liat",
                'Lokasi_IUP' => "IUP Mliwang 2",
                'Tipe_SD_Cadangan' => "Cadangan Terbukti",
                'SD_Cadangan_ton' => 46286740, 
                'Catatan' => null,
                'Status_Penyelidikan' => null,
                'Acuan' =>null,
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Kerek",
                'Luas_ha' => 134.2,  
                'masa_berlaku_iup' =>Carbon::create(2031, 12, 31),
                'masa_berlaku_ppkh' =>Carbon::create(2031, 12, 31),
            ],
            [
                'cadpot_id' => 56,
                'opco_id'=> 3,
                'Jarak' =>   30.7, 
                'latitude' =>-6.7901,  // Latitude
                'longitude' => 111.69463, // Longitude
                'No_ID' => 418200, 
                'Komoditi' => "Pot Tanah Liat",
                'Lokasi_IUP' => "Lestari",
                'Tipe_SD_Cadangan' => "Cadangan Terbukti",
                'SD_Cadangan_ton' =>27080, 
                'Catatan' => "Luas 6,35 Ha, Asumsi Bj 2,5 ton/m3",
                'Status_Penyelidikan' => "Operasi Produksi",
                'Acuan' => "Tabulasi Rekon Minerba Tahun 2020, SDR SUGIHARNI",
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Bancar",
                'Luas_ha' => 6.35,  
                'masa_berlaku_iup' => null,
                'masa_berlaku_ppkh' =>null,
            ],
            [
                'cadpot_id' => 57,
                'opco_id'=> 3,
                'Jarak' =>   28.5, 
                'latitude' =>-6.78717,  // Latitude
                'longitude' => 111.74307, // Longitude
                'No_ID' => 402100, 
                'Komoditi' => "Pot Pasirkuarsa",
                'Lokasi_IUP' => "Sembungin",
                'Tipe_SD_Cadangan' => "Cadangan Terbukti",
                'SD_Cadangan_ton' => 795.000, 
                'Catatan' => "Luas 8,45 Ha",
                'Status_Penyelidikan' => "Operasi Produksi",
                'Acuan' => "Tabulasi Rekon Minerba Tahun 2020, Sdr Sugiarto",
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Bancar",
                'Luas_ha' => 8.45,  
                'masa_berlaku_iup' => null,
                'masa_berlaku_ppkh' =>null,
            ],
            [
                'cadpot_id' => 58,
                'opco_id'=> 3,
                'Jarak' => 38.6, 
                'latitude' =>-6.80899,  // Latitude
                'longitude' => 111.69651, // Longitude
                'No_ID' => 401400, 
                'Komoditi' => "Pot Pasirkuarsa",
                'Lokasi_IUP' => "Ngujuran",
                'Tipe_SD_Cadangan' => "Cadangan Terbukti",
                'SD_Cadangan_ton' =>  1150000, 
                'Catatan' => " Luas 4,92 Ha ",
                'Status_Penyelidikan' => "Operasi Produksi",
                'Acuan' => "Tabulasi Rekon Minerba Tahun 2020, Sdr Khozim",
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Bancar",
                'Luas_ha' => 4.92,  
                'masa_berlaku_iup' => null,
                'masa_berlaku_ppkh' =>null,
            ],
            [
                'cadpot_id' => 59,
                'opco_id'=> 3,
                'Jarak' =>   39.2,
                'latitude' =>-6.83421,  // Latitude
                'longitude' => 111.67797, // Longitude
                'No_ID' => 401200, 
                'Komoditi' => "Pot Pasirkuarsa",
                'Lokasi_IUP' => "Ngepon",
                'Tipe_SD_Cadangan' => "Cadangan Terbukti",
                'SD_Cadangan_ton' =>1082774, 
                'Catatan' => "Luas 2,62 Hektar. Rencana Produksi tahun 2022, 124.800 ton/tahun",
                'Status_Penyelidikan' => "Operasi Produksi",
                'Acuan' => "RKAB Tahun 2022, A.n. Agus Santoso",
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Jatirogo",
                'Luas_ha' => 2.62,  
                'masa_berlaku_iup' => null,
                'masa_berlaku_ppkh' =>null,
            ],
            [
                'cadpot_id' => 60,
                'opco_id'=> 3,
                'Jarak' =>36.6, 
                'latitude' =>-6.78239,  // Latitude
                'longitude' => 111.70255, // Longitude
                'No_ID' => 402000, 
                'Komoditi' => "Pot Pasirkuarsa",
                'Lokasi_IUP' => "Latsari",
                'Tipe_SD_Cadangan' => "Cadangan Terbukti",
                'SD_Cadangan_ton' =>122174, 
                'Catatan' => "Luas 5,02 Ha",
                'Status_Penyelidikan' => "Operasi Produksi",
                'Acuan' => "Tabulasi Rekon Minerba Tahun 2020, PT. SELO JOYO",
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Bancar",
                'Luas_ha' => 5.02,  
                'masa_berlaku_iup' => null,
                'masa_berlaku_ppkh' =>null,
            ],

            [
                'cadpot_id' => 61,
                'opco_id'=> 3,
                'Jarak' =>36.6, 
                'latitude' =>-6.78321,  // Latitude
                'longitude' => 111.68305, // Longitude
                'No_ID' => 401300, 
                'Komoditi' => "Pot Pasirkuarsa",
                'Lokasi_IUP' => "Latsari",
                'Tipe_SD_Cadangan' => "Cadangan Terbukti",
                'SD_Cadangan_ton' =>64776, 
                'Catatan' => "Luas 1,78 Ha",
                'Status_Penyelidikan' => "Operasi Produksi",
                'Acuan' => "Tabulasi Rekon Minerba Tahun 2020, Sdr Karmidi",
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Bancar",
                'Luas_ha' =>1.78,  
                'masa_berlaku_iup' => null,
                'masa_berlaku_ppkh' =>null,
            ], 
            [
                'cadpot_id' => 62,
                'opco_id'=> 3,
                'Jarak' => 37.5, 
                'latitude' =>-6.78758,  // Latitude
                'longitude' => 111.67117, // Longitude
                'No_ID' => 401100, 
                'Komoditi' => "Pot Pasirkuarsa",
                'Lokasi_IUP' => "Tlogoagung",
                'Tipe_SD_Cadangan' => "Cadangan Terbukti",
                'SD_Cadangan_ton' => 454835, 
                'Catatan' => "Luas 1,87 Ha. Asumsi Bj 2,65 ton/m3",
                'Status_Penyelidikan' => "Operasi Produksi",
                'Acuan' => "Tabulasi Rekon Minerba Tahun 2020, Sdr Mahsum",
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Bancar",
                'Luas_ha' => 1.87,  
                'masa_berlaku_iup' => null,
                'masa_berlaku_ppkh' =>null,
            ],
            [
                'cadpot_id' => 63,
                'opco_id'=> 3,
                'Jarak' => 37.5, 
                'latitude' =>-6.79030,  // Latitude
                'longitude' => 111.67117,// Longitude
                'No_ID' => 400600, 
                'Komoditi' => "Pot Pasirkuarsa",
                'Lokasi_IUP' => "Tlogoagung",
                'Tipe_SD_Cadangan' => "Cadangan Terbukti",
                'SD_Cadangan_ton' => 1104001,
                'Catatan' => "Luas 4,75 Ha. Asumsi Bj 2,65 ton/m3",
                'Status_Penyelidikan' => "Eksplorasi",
                'Acuan' => "Tabulasi Rekon Minerba Tahun 2020, Sdr Agus santoso",
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Bancar",
                'Luas_ha' => 4.75,  
                'masa_berlaku_iup' => null,
                'masa_berlaku_ppkh' =>null,
            ],
            [
                'cadpot_id' => 64,
                'opco_id'=> 3,
                'Jarak' => 41.7, 
                'latitude' => -6.79562,  // Latitude
                'longitude' => 111.65511,// Longitude
                'No_ID' => 437600, 
                'Komoditi' => "Pot Pasirkuarsa",
                'Lokasi_IUP' => "Tawangrejo",
                'Tipe_SD_Cadangan' => "Cadangan Terbukti",
                'SD_Cadangan_ton' =>  445725,
                'Catatan' => "Luas 6,1 Hektar",
                'Status_Penyelidikan' =>null,
                'Acuan' => "Agus Santosa, RKAB 2022",
                'Kabupaten' => "Rembang",
                'Kecamatan' => "Sarang",
                'Luas_ha' => 6.1,  
                'masa_berlaku_iup' => null,
                'masa_berlaku_ppkh' =>null,
            ],


        
            // Additional entries can be added here following the same structure
        ];

        DB::table('m_cadangan_potensi')->insert($data);
    }
}
