<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CadanganbbSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'cadanganbb_id' => 1,
                'opco_id' => 1,
                'latitude' => -6.88402,
                'longitude' => 111.92780,
                'Jarak' => 3.2,
                'Luas_ha' => 752.8,
                'Kebutuhan_pertahun_ton' => 14685000,
                'Komoditi' => "Batugamping",
                'Lokasi_IUP' => "IUP BG Temandang",
                'SD_Cadangan_ton' => 180290209,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => "Sudah Dibebaskan",
                'Catatan' => "Rekonsiliasi cadangan Internal Holding Tuban Tahun 2021, Luas 752,8 Hektar. Produksi 16,236,480 ton/tahun.",
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Merakurak,Kerek",
                'Masa_Berlaku_IUP' => Carbon::create(2029, 5, 14),
                'Masa_berlaku_PPKH' => Carbon::create(2029, 5, 14),
            ],
            [
                'cadanganbb_id' => 2,
                'opco_id' => 1,
                'latitude' => -6.89220,
                'longitude' => 111.95458,
                'Jarak' =>  11.6,
                'Luas_ha' => 458.9,
                'Kebutuhan_pertahun_ton' => 14685000,
                'Komoditi' => "Batugamping",
                'Lokasi_IUP' => "IUP BG Tuwiri",
                'SD_Cadangan_ton' => 160602000,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => " Belum Dibebaskan",
                'Catatan' => "Progres Perizinan, Data Eksplorasi oleh LAPI ITB Tahun 2014, CaO 46% - 54%, MgO < 2%, Luas 458,9 Hektar. NO. SK IUP OP 188.45/1155 IUP/KPTS/414.058/2012",
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Merakurak,Kerek",
                'Masa_Berlaku_IUP' => Carbon::create(2032, 3, 27),
                'Masa_berlaku_PPKH' => Carbon::create(2032, 3, 27),
            ],
            [
                'cadanganbb_id' => 3,
                'opco_id' => 1,
                'latitude' => -6.850910,
                'longitude' => 111.936740,
                'Jarak' => 2.8,
                'Luas_ha' => 120.04,
                'Kebutuhan_pertahun_ton' => 3058000,
                'Komoditi' => "Tanah Liat",
                'Lokasi_IUP' => "IUP Clay Tlogowaru",
                'SD_Cadangan_ton' => 4982366,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => "Sudah Dibebaskan",
                'Catatan' => "Perubahan luasan IUP OP Tahun 2018 karena beberapa blok sudah selesai ditambang dan ada status sosial blok IX dan X diperlukan penyelesaian. Q1 = 5.074.184 , Q2 = 5.037.392, NO. SK IUP OP : P2T/80/15.02/VIII/2018",
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Merakurak,Kerek",
                'Masa_Berlaku_IUP' => Carbon::create(2033, 8, 6),
                'Masa_berlaku_PPKH' => null,
            ],
            [
                'cadanganbb_id' => 4,
                'opco_id' => 1,
                'latitude' => -6.83144,
                'longitude' => 111.90826,
                'Jarak' =>  10.4,
                'Luas_ha' => 201.6,
                'Kebutuhan_pertahun_ton' => 3058000,
                'Komoditi' => "Tanah Liat",
                'Lokasi_IUP' => "IUP Clay Mliwang",
                'SD_Cadangan_ton' => 1789302,
                'Status_Penyelidikan' => "Eksplorasi",
                'Status_Pembebasan' => "Sudah Dibebaskan",
                'Catatan' => "IUP Eksplorasi 812021402140236170034. Perubahan luasan IUP OP karena beberapa blok sudah selesai di tambang dan ada beberapa titik masuk lahan TKD Desa Tobo, NO. SK IUP OP : P2T/8/15.02/02/XI/2017",
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Kerek",
                'Masa_Berlaku_IUP' => Carbon::create(2022, 12, 31),
                'Masa_berlaku_PPKH' => null,
            ],
            [
                'cadanganbb_id' => 5,
                'opco_id' => 1,
                'latitude' => -6.83671,
                'longitude' => 111.89629,
                'Jarak' => 6.6,
                'Luas_ha' => 5,
                'Kebutuhan_pertahun_ton' => 3058000,
                'Komoditi' => "Tanah Liat",
                'Lokasi_IUP' => "IUP Clay Tobo",
                'SD_Cadangan_ton' =>  748651,
                'Status_Penyelidikan' => " Operasi Produksi",
                'Status_Pembebasan' => "Sebagian Dibebaskan",
                'Catatan' => "Penguasaan lahan baru di Q3 2024 sekitar 90%, NO. SK IUP OP : P2T/83/15.02/XI/2020",
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Merakurak",
                'Masa_Berlaku_IUP' => Carbon::create(2024, 11, 15),
                'Masa_berlaku_PPKH' => null,
            ],
            [
                'cadanganbb_id' => 6,
                'opco_id' => 1,
                'latitude' => -6.82047,
                'longitude' => 111.91368,
                'Jarak' =>  5.7,
                'Luas_ha' => 35.75,
                'Kebutuhan_pertahun_ton' => 3058000,
                'Komoditi' => "Tanah Liat",
                'Lokasi_IUP' => "IUP Clay Karangasem",
                'SD_Cadangan_ton' => 2893654,
                'Status_Penyelidikan' => "Eksplorasi",
                'Status_Pembebasan' => " Sebagian Dibebaskan ",
                'Catatan' => "Penguasaan lahan baru di Q3 2024 sekitar 53%, NO. SK IUP OP : P2T/84/15.02/XI/2019",
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Jenu",
                'Masa_Berlaku_IUP' => Carbon::create(2024, 11, 15),
                'Masa_berlaku_PPKH' => null,
            ],
            [
                'cadanganbb_id' => 7,
                'opco_id' => 2,
                'latitude' => -6.86877,
                'longitude' => 111.51146,
                'Jarak' => 9.8,
                'Luas_ha' => 293.1,
                'Kebutuhan_pertahun_ton' => 3480000,
                'Komoditi' => "Batugamping",
                'Lokasi_IUP' => "IUP BG Tegaldowo",
                'SD_Cadangan_ton' => 255331678,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => " Sebagian Dibebaskan ",
                'Catatan' => "Terdapat lahan SHM Masyarakat desa di dalam IUP yang belum dapat dibebaskan Tahun 2021, Q1 = 256.293.761, Q2 = 255.816.842, NO. SK IUP OP : 543.32/1529/2017",
                'Kabupaten' => "Rembang",
                'Kecamatan' => "Gunem",
                'Masa_Berlaku_IUP' => Carbon::create(2037, 3, 2),
                'Masa_berlaku_PPKH' => null,
            ],
            [
                'cadanganbb_id' => 8,
                'opco_id' => 2,
                'latitude' => -6.86935,
                'longitude' => 111.46668,
                'Jarak' => 5.1,
                'Luas_ha' => 98.9,
                'Kebutuhan_pertahun_ton' => 720000,
                'Komoditi' => "Tanah Liat",
                'Lokasi_IUP' => "IUP Clay Kajar",
                'SD_Cadangan_ton' => 14983796,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => " Sebagian Dibebaskan ",
                'Catatan' => "Terdapat lahan SHM Masyarakat desa dan Alur Perhutani (Tanah DK) di dalam IUP yang belum dapat dibebaskan Tahun 2021, NO. SK IUP OP : 543.32/1712/2017",
                'Kabupaten' => "Rembang",
                'Kecamatan' => "Gunem",
                'Masa_Berlaku_IUP' => Carbon::create(2037, 3, 8),
                'Masa_berlaku_PPKH' => Carbon::create(2037, 3, 8),
            ],
            [
                'cadanganbb_id' => 9,
                'opco_id' => 3,
                'latitude' => -6.84107,
                'longitude' => 111.86257,
                'Jarak' => 11.3,
                'Luas_ha' => 573.83,
                'Kebutuhan_pertahun_ton' => 5200000,
                'Komoditi' => "Batugamping",
                'Lokasi_IUP' => "IUP BG Sawir",
                'SD_Cadangan_ton' =>  547181582,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => " Sudah dibebaskan",
                'Catatan' => "IUP 2020. Luas 573,83 Ha, , Rekonsiliasi Cadangan Internal Anak Usaha Tuban Tahun 2022, NO. SK IUP OP : 15.02/26/VII/2020",
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Sawir, Kedungrejo",
                'Masa_Berlaku_IUP' => Carbon::create(2034, 12, 12),
                'Masa_berlaku_PPKH' =>  Carbon::create(2034, 12, 12),
            ],
            [
                'cadanganbb_id' => 10,
                'opco_id' => 3,
                'latitude' => -6.83099,
                'longitude' => 111.87674,
                'Jarak' => 10.4,
                'Luas_ha' => 134.2,
                'Kebutuhan_pertahun_ton' =>2500000,
                'Komoditi' => "Tanah Liat",
                'Lokasi_IUP' => "IUP Clay Mliwang 1",
                'SD_Cadangan_ton' => 45795421,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => " Sudah dibebaskan",
                'Catatan' => "NO. SK IUP OP : 2128/1/IUP/PMDN/2021, Sesuai dengan perhitungan awal.",
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Kerek",
                'Masa_Berlaku_IUP' => Carbon::create(2024, 12, 12),
                'Masa_Berlaku_PPKH' => Carbon::create(2024, 12, 12),
            ],
            [
                'cadanganbb_id' => 11,
                'opco_id' => 3,
                'latitude' => -6.82541,
                'longitude' => 111.89650,
                'Jarak' => 10.4,
                'Luas_ha' => 33,
                'Kebutuhan_pertahun_ton' =>2500000,
                'Komoditi' => "Tanah Liat",
                'Lokasi_IUP' => "IUP Clay Mliwang 2",
                'SD_Cadangan_ton' => 10000000,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => "Belum dibebaskan",
                'Catatan' => "Progres Persiapan Jalan Hauling , IUP 2020, Luas 33 Ha, NO. SK IUP OP : 91204098120150000",
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Kerek",
                'Masa_Berlaku_IUP' => Carbon::create(2031, 12, 31),
                'Masa_Berlaku_PPKH' => Carbon::create(2031, 12, 31),
            ],
            [
                'cadanganbb_id' => 12,
                'opco_id' => 4,
                'latitude' => -4.78678,
                'longitude' => 119.62644,
                'Jarak' => 3.9,
                'Luas_ha' => 214.5,
                'Kebutuhan_pertahun_ton' =>9000000,
                'Komoditi' => "Batugamping",
                'Lokasi_IUP' => "IUP BG Biringere",
                'SD_Cadangan_ton' => 150500529,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => "Sudah dibebaskan",
                'Catatan' => "Luas 214,5 hektar. No. SK IUP/IUPK 95/I.03/PTSP/2018, Rekonsiliasi data deviasi level kedalaman lubang bor",
                'Kabupaten' => "Pangkajene Kepulauan",
                'Kecamatan' => "Bungoro",
                'Masa_Berlaku_IUP' => Carbon::create(2028, 6, 5),
                'Masa_Berlaku_PPKH' => null,
            ],
            [
                'cadanganbb_id' => 13,
                'opco_id' => 4,
                'latitude' => -4.81041,
                'longitude' => 119.60537,
                'Jarak' => 5.1,
                'Luas_ha' => 280,
                'Kebutuhan_pertahun_ton' =>2000000,
                'Komoditi' => "Tanah Liat",
                'Lokasi_IUP' => "IUP Clay Bontoa",
                'SD_Cadangan_ton' => 162054,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => "Sudah dibebaskan",
                'Catatan' => "Luas 280 hektar. Nomor SK IUP /IUPK 23/I.03a/PTSP/2019, Rekonsiliasi data deviasi level kedalaman lubang bor, Q1 = 640.615 , Q2 = 430.820",
                'Kabupaten' => "Pangkajene Kepulauan",
                'Kecamatan' => "Minnasatene",
                'Masa_Berlaku_IUP' => Carbon::create(2024, 12, 29),
                'Masa_Berlaku_PPKH' => null,
            ],
            [
                'cadanganbb_id' => 14,
                'opco_id' => 4,
                'latitude' => -4.80300,
                'longitude' => 119.68100,
                'Jarak' =>  11.0,
                'Luas_ha' => 14,
                'Kebutuhan_pertahun_ton' =>2000000,
                'Komoditi' => "Tanah Liat",
                'Lokasi_IUP' => "IUP Clay Bulu Tellue",
                'SD_Cadangan_ton' => 4723048,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => "Sudah dibebaskan",
                'Catatan' => "Rekonsiliasi data deviasi level kedalaman lubang bor,NO. SK IUP OP : 39/I.03a.P/P2T/10/2017",
                'Kabupaten' => "Pangkajene Kepulauan",
                'Kecamatan' => "Tondong Tallasa",
                'Masa_Berlaku_IUP' => Carbon::create(2022, 7, 29),
                'Masa_Berlaku_PPKH' => null,
            ],                              
            [
                'cadanganbb_id' => 15,
                'opco_id' => 4,
                'latitude' => -4.80300,
                'longitude' => 119.68100,
                'Jarak' =>  12.0,
                'Luas_ha' => 9.37,
                'Kebutuhan_pertahun_ton' =>2000000,
                'Komoditi' => "Tanah Liat",
                'Lokasi_IUP' => "IUP Clay Bulu Tellue",
                'SD_Cadangan_ton' => 3551143,
                'Status_Penyelidikan' => "Eksplorasi",
                'Status_Pembebasan' => "Sudah dibebaskan",
                'Catatan' => "Luas 9,37 hektar. Nomor SK IUP 10/I.01/PTSP/2020, Rekonsiliasi data berdasarkan interpretasi awal berdasarkan test pit.",
                'Kabupaten' => "Pangkajene Kepulauan",
                'Kecamatan' => "Minnasatene",
                'Masa_Berlaku_IUP' => Carbon::create(2025, 11, 30),
                'Masa_Berlaku_PPKH' => null,
            ],  
            [
                'cadanganbb_id' => 16,
                'opco_id' => 4,
                'latitude' => -4.90300,
                'longitude' => 119.64800,
                'Jarak' =>  20.8,
                'Luas_ha' => 45.7,
                'Kebutuhan_pertahun_ton' =>2000000,
                'Komoditi' => "Tanah Liat",
                'Lokasi_IUP' => "IUP Clay Tonasa",
                'SD_Cadangan_ton' => 4420784,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => "Sudah dibebaskan",
                'Catatan' => "Luas 45,7 Ha, Rekonsiliasi data deviasi level kedalaman lubang bor. NO. SK IUP OP : 81200018506210065",
                'Kabupaten' => "Pangkajene Kepulauan",
                'Kecamatan' => "Balocci",
                'Masa_Berlaku_IUP' => Carbon::create(2030, 12, 30),
                'Masa_Berlaku_PPKH' => null,
            ], 
            [
                'cadanganbb_id' => 17,
                'opco_id' => 4,
                'latitude' => -4.79500,
                'longitude' => 119.68100,
                'Jarak' => 12.0,
                'Luas_ha' => 83,
                'Kebutuhan_pertahun_ton' =>2000000,
                'Komoditi' => "Tanah Liat",
                'Lokasi_IUP' => "IUP Clay Paccola",
                'SD_Cadangan_ton' => 42186993,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => "Sudah dibebaskan",
                'Catatan' => "Luas 83 hektar. Nomor SK IUP /IUPK 1/I.03.P/P2T/01/2016, PPKH Hutan Produksi Bulu Poccola",
                'Kabupaten' => "Pangkajene Kepulauan",
                'Kecamatan' => "Tondong Tallasa",
                'Masa_Berlaku_IUP' => Carbon::create(2026, 1, 20),
                'Masa_Berlaku_PPKH' => null,
            ],   
            [
                'cadanganbb_id' => 18,
                'opco_id' => 4,
                'latitude' => -4.71505,
                'longitude' =>119.58854,
                'Jarak' => 15.6,
                'Luas_ha' =>423.877,
                'Kebutuhan_pertahun_ton' =>2000000,
                'Komoditi' => "Tanah Liat",
                'Lokasi_IUP' => "IUP Clay Ma'rang",
                'SD_Cadangan_ton' => 3603064,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => "Sudah dibebaskan",
                'Catatan' => "NO. SK IUP OP : 81200018506210000, FS Tahun 2023",
                'Kabupaten' => "Pangkajene Kepulauan",
                'Kecamatan' => "Ma'rang",
                'Masa_Berlaku_IUP' => Carbon::create(2044, 4, 21),
                'Masa_Berlaku_PPKH' => null,
            ],
            [
                'cadanganbb_id' => 19,
                'opco_id' => 5,
                'latitude' => -6.47099,
                'longitude' => 106.94209,
                'Jarak' =>  2.5,
                'Luas_ha' => 724.12, 
                'Kebutuhan_pertahun_ton' => 6600000,
                'Komoditi' => "Batugamping",
                'Lokasi_IUP' => "IUP BG Klapanunggal",
                'SD_Cadangan_ton' =>  360175571,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => "Sudah dibebaskan",
                'Catatan' => "540/37/29.1.07.2/DPMP TSP/2020, Data rekonsiliasi Q1 2023",
                'Kabupaten' => "Narogong",
                'Kecamatan' => "Klapanunggal",
                'Masa_Berlaku_IUP' => Carbon::create(2032, 9, 20),
                'Masa_Berlaku_PPKH' => Carbon::create(2032, 9, 20),
            ],  
            [
                'cadanganbb_id' => 20,
                'opco_id' => 5,
                'latitude' => -6.47854,
                'longitude' => 106.92172,
                'Jarak' => 8.7,
                'Luas_ha' => 216.12,
                'Kebutuhan_pertahun_ton' =>850000,
                'Komoditi' => "Tanah Liat",
                'Lokasi_IUP' => "IUP Clay Klapanunggal",
                'SD_Cadangan_ton' => 56984502,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => "Sudah dibebaskan",
                'Catatan' => "540/23/29.1.07.2/DPMP TSP/2020, Data rekonsiliasi Q1 2023",
                'Kabupaten' => "Narogong",
                'Kecamatan' => "Klapanunggal",
                'Masa_Berlaku_IUP' => Carbon::create(2026, 7, 28),
                'Masa_Berlaku_PPKH' => null,
            ],  
            [
                'cadanganbb_id' => 21,
                'opco_id' => 6,
                'latitude' => -7.74270,
                'longitude' => 108.97786, 
                'Jarak' => 7.8,
                'Luas_ha' => 998.5,
                'Kebutuhan_pertahun_ton' => 3800000,
                'Komoditi' => "Batugamping",
                'Lokasi_IUP' => "IUP BG P. Nusakambangan",
                'SD_Cadangan_ton' => 99583233,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => "Sudah dibebaskan",
                'Catatan' => "503/IUP- OP/3301.4.40.16, Rekonsiliasi Cadangan Internal Anak Usaha Cilacap Tahun 2021",
                'Kabupaten' => "P. Nusakambangan",
                'Kecamatan' => "Cilacap Selatan",
                'Masa_Berlaku_IUP' => Carbon::create(2033, 9, 19),
                'Masa_Berlaku_PPKH' => null,
            ],
            [
                'cadanganbb_id' => 22,
                'opco_id' => 6,
                'latitude' => -7.64185,
                'longitude' => 109.05011,
                'Jarak' => 9.9,
                'Luas_ha' => 233.5,
                'Kebutuhan_pertahun_ton' => 425000,
                'Komoditi' => "Tanah Liat",
                'Lokasi_IUP' => "IUP Clay Jeruk Legi",
                'SD_Cadangan_ton' => 7769997,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => "Sudah dibebaskan",
                'Catatan' => "503/IUP- OP/3301.4.39.15,Rekonsiliasi Cadangan Internal Anak Usaha Cilacap Tahun 2021",
                'Kabupaten' => "Cilacap",
                'Kecamatan' => "Jeruk Legi",
                'Masa_Berlaku_IUP' => Carbon::create(2033, 9, 19),
                'Masa_Berlaku_PPKH' => null,
            ],
            [
                'cadanganbb_id' => 23,
                'opco_id' => 7,
                'latitude' => -5.44907,
                'longitude' => 95.25173,
                'Jarak' => 1.4,
                'Luas_ha' => 150, 
                'Kebutuhan_pertahun_ton' => 1700000,
                'Komoditi' => "Batugamping",
                'Lokasi_IUP' => "IUP BG Gle Lubo",
                'SD_Cadangan_ton' => 26915848,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => "Sudah dibebaskan",
                'Catatan' => "SK No.540/DPMPTSP/1619/IU P-OP2/2022, FS Tahun 2016",
                'Kabupaten' => "Aceh Besar",
                'Kecamatan' => "Lhoknga",
                'Masa_Berlaku_IUP' => Carbon::create(2032, 9, 20),
                'Masa_Berlaku_PPKH' => null,
            ], 
            [
                'cadanganbb_id' => 24,
                'opco_id' => 7,
                'latitude' => 5.47225,
                'longitude' => 95.25758,
                'Jarak' =>  5.5,
                'Luas_ha' => 50.5, 
                'Kebutuhan_pertahun_ton' => 500000,
                'Komoditi' => "Tanah Liat",
                'Lokasi_IUP' => "IUP Clay Gle Lubo",
                'SD_Cadangan_ton' => 6904561,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => "Sudah dibebaskan",
                'Catatan' => "SK No.540/DPMPTSP/1620/IU P-OP2/2022, FS Tahun 2016",
                'Kabupaten' => "Aceh Besar",
                'Kecamatan' => "Lhoknga",
                'Masa_Berlaku_IUP' => Carbon::create(2032, 9, 2),
                'Masa_Berlaku_PPKH' => null,
            ],
            [
                'cadanganbb_id' => 25,
                'opco_id' => 8,
                'latitude' => -0.97128,
                'longitude' => 100.47476,
                'Jarak' => 4.6,
                'Luas_ha' => 206.96,
                'Kebutuhan_pertahun_ton' => 8100000,
                'Komoditi' => "Batugamping",
                'Lokasi_IUP' => "IUP BG Pit Limit Karang Putih",
                'SD_Cadangan_ton' => 20624797,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => "Sudah dibebaskan",
                'Catatan' => "SK No 540/04- PERIZ/DPMPTSP/I-2023, Data rekonsiliasi Q1 2023, Q1 = 21.463.272, Q2 = 20.948.581, NO. SK IUP OP : 540/04-PERIZ/DPMPTSP/I-2023",
                'Kabupaten' => "Kota Padang",
                'Kecamatan' => "Lubuk Kilangan",
                'Masa_Berlaku_IUP' => Carbon::create(2033, 4, 21),
                'Masa_Berlaku_PPKH' => null,
            ],
            [
                'cadanganbb_id' => 26,
                'opco_id' => 8,
                'latitude' => -0.97763,
                'longitude' => 100.48865,
                'Jarak' => 5.5,
                'Luas_ha' => 329.89,
                'Kebutuhan_pertahun_ton' => 8100000,
                'Komoditi' => "Batugamping",
                'Lokasi_IUP' => "IUP BG Tajarang",
                'SD_Cadangan_ton' => 326683460,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => "Sudah dibebaskan",
                'Catatan' => "Update Q3, SK No 544-81-2018, Data rekonsiliasi Q1 2023, NO. SK IUP OP : 544-81-2018",
                'Kabupaten' => "Kota Padang",
                'Kecamatan' => "Lubuk Kilangan",
                'Masa_Berlaku_IUP' => Carbon::create(2042, 9, 30),
                'Masa_Berlaku_PPKH' => null,
            ],
            [
                'cadanganbb_id' => 27,
                'opco_id' => 8,
                'latitude' => -0.94161,
                'longitude' => 100.48362,
                'Jarak' => 3.0,
                'Luas_ha' => 88.92,
                'Kebutuhan_pertahun_ton' =>800000,
                'Komoditi' => "Tanah Liat",
                'Lokasi_IUP' => "IUP Clay Bukit Atas / Padayo",
                'SD_Cadangan_ton' => 2314765,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => "Sudah dibebaskan",
                'Catatan' => "SK No 540/03- PERIZ/DPMPTSP/I-2023, FS Tahun 2021, Q1 = 2.326.665, Q2 = 2.318.640, NO. SK IUP OP : 540/03-PERIZ/DPMPTSP/I-2023",
                'Kabupaten' => "Kota Padang",
                'Kecamatan' => "Lubuk Kilangan",
                'Masa_Berlaku_IUP' => Carbon::create(2033, 4, 21),
                'Masa_Berlaku_PPKH' => null,
            ], 
            [
                'cadanganbb_id' => 28,
                'opco_id' => 8,
                'latitude' => -0.97763,
                'longitude' => 100.48865,
                'Jarak' => 5.5,
                'Luas_ha' => 329.89,
                'Kebutuhan_pertahun_ton' => 800000,
                'Komoditi' => "Tanah Liat",
                'Lokasi_IUP' => "IUP Clay Tajarang",
                'SD_Cadangan_ton' => 16475444,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => "Sudah dibebaskan",
                'Catatan' => "SK No 544-81-2018, FS Tahun 2021,  NO. SK IUP OP : 540/02-PERIZ/DPMPTSP/I-2023",
                'Kabupaten' => "Kota Padang",
                'Kecamatan' => "Lubuk Kilangan",
                'Masa_Berlaku_IUP' => Carbon::create(2042, 9, 30),
                'Masa_Berlaku_PPKH' => null,
            ], 
            [
                'cadanganbb_id' => 29,
                'opco_id' => 8,
                'latitude' => -0.97519,
                'longitude' => 100.48330,
                'Jarak' =>5.5,
                'Luas_ha' => 536.85,
                'Kebutuhan_pertahun_ton' => 496849, 
                'Komoditi' => "Pasirkuarsa",
                'Lokasi_IUP' => "IUP Silica Karang Putih & Tajarang",
                'SD_Cadangan_ton' => 44486584,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => "Sudah dibebaskan",
                'Catatan' => "540/01- PERIZ/DPMPTSP/I-2023, FS Tahun 2021, Q1 = 44.663.419 , Q2 = 44.582.906, NO. SK IUP OP : 540/01-PERIZ/DPMPTSP/I-2023",
                'Kabupaten' => "Kota Padang",
                'Kecamatan' => "Lubuk Kilangan",
                'Masa_Berlaku_IUP' => Carbon::create(2042, 9, 30),
                'Masa_Berlaku_PPKH' => null,
            ],
            [
                'cadanganbb_id' => 30,
                'opco_id' => 8,
                'latitude' => -0.95744,
                'longitude' => 100.48761,
                'Jarak' => 4.0,
                'Luas_ha' => 107.2,
                'Kebutuhan_pertahun_ton' => 496849, 
                'Komoditi' => "Pasirkuarsa",
                'Lokasi_IUP' => "IUP Silica Rijang Ngalau",
                'SD_Cadangan_ton' => 190292,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => "Sudah dibebaskan",
                'Catatan' => "Mine Out Telah Selesai Ditambang Sejak 2015, NO .SK IUP OP : 91205049908210000.",
                'Kabupaten' => "Kota Padang",
                'Kecamatan' => "Padang Panjang",
                'Masa_Berlaku_IUP' => Carbon::create(2028, 4, 21),
                'Masa_Berlaku_PPKH' => null,
            ],
            [
                'cadanganbb_id' => 31,
                'opco_id' => 8,
                'latitude' => -0.91234,
                'longitude' => 100.51234,
                'Jarak' =>  5.5,
                'Luas_ha' => 536.85,
                'Kebutuhan_pertahun_ton' => 41400,
                'Komoditi' => "Trass",
                'Lokasi_IUP' => "IUP Trass Bukit Ngalau",
                'SD_Cadangan_ton' => 7426574,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => "Sudah dibebaskan",
                'Catatan' => "540/7- PERIZ/DPMPTSP/IX- 2022, FS Tahun 2021, Q1 = 7.440.162, Q2 = 7.432.201, NO. SK IUP OP : 540/7-PERIZ/DPMPTSP/IX-2022",
                'Kabupaten' => "Kota Padang",
                'Kecamatan' => "Lubuk Kilangan",
                'Masa_Berlaku_IUP' => Carbon::create(2027, 9, 30),
                'Masa_Berlaku_PPKH' => null,
            ],
            [
                'cadanganbb_id' => 32,
                'opco_id' => 8,
                'latitude' => -0.97128,
                'longitude' => 100.47476,
                'Jarak' =>  4.6,
                'Luas_ha' => 206.96,
                'Kebutuhan_pertahun_ton' => 216000,
                'Komoditi' => "Agregat Basalt",
                'Lokasi_IUP' => "IUP Basalt Eksisting Karang Putih",
                'SD_Cadangan_ton' =>  14752139,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => "Sudah dibebaskan",
                'Catatan' => "NO. SK IUP OP : 91205048904210039, FS Tahun 2021",
                'Kabupaten' => "Kota Padang",
                'Kecamatan' => "Lubuk Kilangan",
                'Masa_Berlaku_IUP' => Carbon::create(2028, 2, 7),
                'Masa_Berlaku_PPKH' => null,
            ],
            [
                'cadanganbb_id' => 33,
                'opco_id' => 8,
                'latitude' => -0.97519,
                'longitude' => 100.48330,
                'Jarak' => 5.5,
                'Luas_ha' => 536.85,
                'Kebutuhan_pertahun_ton' => 216000,
                'Komoditi' => "Granit",
                'Lokasi_IUP' => "IUP Granit Bukit Ngalau",
                'SD_Cadangan_ton' => 600928,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => "Sudah dibebaskan",
                'Catatan' => "NO. SK IUP OP : 540/6-PERIZ/DPMPTSP/IX-2022, FS Tahun 2021",
                'Kabupaten' => "Kota Padang",
                'Kecamatan' => "Lubuk Kilangan",
                'Masa_Berlaku_IUP' => Carbon::create(2027, 9, 30),
                'Masa_Berlaku_PPKH' => null,
            ],
            [
                'cadanganbb_id' => 34,
                'opco_id' => 9,
                'latitude' => -4.18754,
                'longitude' => 104.13489,
                'Jarak' => 1.2,
                'Luas_ha' => 118.7,
                'Kebutuhan_pertahun_ton' => 3500000,
                'Komoditi' => "Batugamping",
                'Lokasi_IUP' => "IUP BG Baturaja T1",
                'SD_Cadangan_ton' => 13490324,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => "Sudah dibebaskan",
                'Catatan' => "IUP OP No.00346/DPMPTSP.V/V/2019, FS LAPI ITB Tahun 2021",
                'Kabupaten' => "Ogan Komering Ulu",
                'Kecamatan' => "Baturaja T1",
                'Masa_Berlaku_IUP' => Carbon::create(2032, 3, 2),
                'Masa_Berlaku_PPKH' => null,
            ],
            [
                'cadanganbb_id' => 35,
                'opco_id' => 9,
                'latitude' => -4.13677,
                'longitude' => 104.13554,
                'Jarak' => 4.4,
                'Luas_ha' => 458.9,
                'Kebutuhan_pertahun_ton' => 3500000,
                'Komoditi' => "Batugamping",
                'Lokasi_IUP' => "IUP BG Baturaja T2",
                'SD_Cadangan_ton' => 47659276,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => "Sudah dibebaskan",
                'Catatan' => "IUP OP No. 269/DPMPTSP.V/VII/2017, FS LAPI ITB Tahun 2020",
                'Kabupaten' => "Ogan Komering Ulu",
                'Kecamatan' => "Baturaja T2",
                'Masa_Berlaku_IUP' => Carbon::create(2032, 7, 28),
                'Masa_Berlaku_PPKH' => null,
            ],
            [
                'cadanganbb_id' => 36,
                'opco_id' => 9,
                'latitude' => -4.20335,
                'longitude' => 104.02909,
                'Jarak' => 30.3,
                'Luas_ha' => 4004,
                'Kebutuhan_pertahun_ton' => 3500000,
                'Komoditi' => "Batugamping",
                'Lokasi_IUP' => "IUP BG Baturaja T3",
                'SD_Cadangan_ton' => 84512100,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => "Sudah dibebaskan",
                'Catatan' => "IUP OP No: 02202053216770017, FS LAPI ITB Tahun 2023, Progres Perizinan Kawasan Hutan",
                'Kabupaten' => "Ogan Komering Ulu",
                'Kecamatan' => "Baturaja T3",
                'Masa_Berlaku_IUP' => Carbon::create(2032, 7, 30),
                'Masa_Berlaku_PPKH' => Carbon::create(2032, 7, 30),
            ],
            [
                'cadanganbb_id' => 37,
                'opco_id' => 9,
                'latitude' => -4.118030,
                'longitude' => 104.15040,
                'Jarak' =>  1.2,
                'Luas_ha' => 101.4,
                'Kebutuhan_pertahun_ton' => 400000,
                'Komoditi' => "Tanah Liat",
                'Lokasi_IUP' => "IUP Clay Baturaja T1",
                'SD_Cadangan_ton' => 1143233,
                'Status_Penyelidikan' => "Operasi Produksi",
                'Status_Pembebasan' => "Sudah dibebaskan",
                'Catatan' => "IUP OP No.0034/DPMPTSP.V/I/2020, Revisi FS LAPI ITB Tahun 2024",
                'Kabupaten' => "Ogan Komering Ulu",
                'Kecamatan' => "Baturaja T1",
                'Masa_Berlaku_IUP' => Carbon::create(2032, 3, 23),
                'Masa_Berlaku_PPKH' => null,
            ],
                            
        ];
        // Perulangan untuk memproses setiap data
        $dataToInsert = [];

        foreach ($data as $item) {
            $today = Carbon::now();

            // Hitung umur cadangan (jika `Kebutuhan_pertahun_ton` tidak nol)
            $umur_cadangan_thn = ($item['Kebutuhan_pertahun_ton'] > 0)
                ? round($item['SD_Cadangan_ton'] / $item['Kebutuhan_pertahun_ton'])
                : null;

            // Hitung umur masa berlaku izin
            $masa_berlaku_iup = $item['Masa_Berlaku_IUP'];
            $selisih = $today->diff($masa_berlaku_iup);

            if ($masa_berlaku_iup->greaterThan($today)) {
                $umur_masa_berlaku_izin = "{$selisih->y} tahun {$selisih->m} bulan";
            } else {
                $umur_masa_berlaku_izin = "Terlewat {$selisih->y} tahun {$selisih->m} bulan";
            }

            // Tambahkan hasil ke array baru
            $dataToInsert[] = array_merge($item, [
                'umur_cadangan_thn' => $umur_cadangan_thn,
                'umur_masa_berlaku_izin' => $umur_masa_berlaku_izin,
            ]);
        }
        DB::table('m_cadangan_bb')->insert($dataToInsert);
    }
}
